"""
Build a JS-friendly lite version of the 11 demo cases for HTML embedding.
Extract: id, name, gene, disease, category, final_score, decision, 4 rounds debate.
"""
import json
from pathlib import Path

OUT = Path('/home/gem/workspace/agent/workspace/causatwin_v0.2/output')
full = json.load(open(OUT / 'v0.2_flash_all_full.json'))
results = full['results']

# Manually attach disease info from digest
digest = json.load(open(OUT / 'v0.2_flash_digest.json'))
details = digest['evaluation']['details']
id_to_disease = {}
for d in details:
    id_to_disease[d['id']] = d['name']  # Will add actual disease later

# Also get disease from the input
# Build lite cases
lite_cases = []
for r in results:
    case_id = r['id']
    gene = r['name']
    
    # Get disease from indications or category
    disease = r.get('indications', '')
    if isinstance(disease, list) and disease:
        disease = disease[0]
    elif not disease:
        # Use target gene's known indications
        disease = {
            'P1': 'Hypercholesterolemia',
            'P2': 'Rheumatoid Arthritis',
            'P3': 'Atherosclerotic Cardiovascular Disease',
            'P4': 'Hypertriglyceridemia',
            'P5': 'Venous Thromboembolism',
            'N1': 'Atherosclerosis',
            'N2': 'ASCVD',
            'N3': 'Type 2 Diabetes',
            'N4': 'Melanoma',
            'N5': 'Atrial Fibrillation Stroke Prevention',
            'A1': "Parkinson Disease"
        }.get(case_id, 'Unknown')
    
    transcript = r.get('transcript', {})
    target_info = transcript.get('target', {})
    rounds = transcript.get('rounds', {})
    
    # Convert rounds to compact format
    rounds_lite = {}
    for rk in ['R1', 'R2', 'R3', 'R4']:
        if rk not in rounds:
            continue
        rd = rounds[rk]
        if 'BEA' not in rd or 'BCA' not in rd or 'MA' not in rd:
            continue
        rounds_lite[rk] = {
            'BEA': {
                'argument': rd['BEA'].get('argument', ''),
                'scores': {k: rd['BEA'].get(k) for k in ['causal_evidence', 'cross_population', 'mr_strength', 'pQTL_signal']}
            },
            'BCA': {
                'argument': rd['BCA'].get('argument', ''),
                'scores': {k: rd['BCA'].get(k) for k in ['druggability', 'modality_feasibility', 'pathway_centrality', 'off_target_risk']}
            },
            'MA': {
                'argument': rd['MA'].get('consensus_summary', rd['MA'].get('argument', '')),
                'scores': {k: rd['MA'].get(k) for k in ['final_score', 'confidence'] if rd['MA'].get(k) is not None}
            }
        }
    
    # Final
    final = {
        'final_score': r.get('final_score'),
        'decision': r.get('decision'),
        'confidence': r.get('confidence'),
        'consensus_summary': r.get('consensus_summary', ''),
        'next_steps': r.get('next_steps', [])
    }
    
    lite_cases.append({
        'id': case_id,
        'gene': gene,
        'disease': disease,
        'category': r.get('category', 'unknown'),
        'final': final,
        'rounds': rounds_lite,
        'expected_score': r.get('expected_score'),
        'expected_decision': r.get('expected_decision'),
        'rationale': r.get('rationale', ''),
    })

# Build JS data file
js_data = '// CausaTwin v0.3 — 11 demo cases (extracted from v0.2_flash_all_full.json)\n'
js_data += '// Generated by build_lite_cases.py\n\n'
js_data += 'const DEMO_CASES = ' + json.dumps(lite_cases, ensure_ascii=False, indent=2) + ';\n\n'
js_data += '// Sample queries for quick buttons\n'
js_data += 'const SAMPLE_QUERIES = [\n'
for c in lite_cases:
    g = c['gene'].split(' (')[0].replace('"', '\\"')
    d = c['disease'].replace('"', '\\"')
    js_data += f"  {{ gene: \"{g}\", disease: \"{d}\" }},\n"
js_data += '  { gene: "TP53", disease: "Lung Cancer" },\n'
js_data += '  { gene: "KRAS", disease: "Pancreatic Cancer" },\n'
js_data += '  { gene: "IL6R", disease: "Crohn Disease" },\n'
js_data += '  { gene: "SNCA", disease: "Parkinson Disease" },\n'
js_data += '  { gene: "GLP1R", disease: "Obesity" },\n'
js_data += '];\n'

# Write to file
out_path = OUT / 'demo_cases_data.js'
out_path.write_text(js_data, encoding='utf-8')
print(f"✅ Built {out_path}")
print(f"  Cases: {len(lite_cases)}")
print(f"  Size: {out_path.stat().st_size:,} bytes")

# Also write knowledge base JS
kb = json.load(open(OUT / 'target_knowledge_base.json'))
kb_js = '// Drug target knowledge base (49 targets)\n'
kb_js += 'const TARGET_KB = ' + json.dumps(kb, ensure_ascii=False, indent=2) + ';\n'

kb_path = OUT / 'target_kb_data.js'
kb_path.write_text(kb_js, encoding='utf-8')
print(f"✅ Built {kb_path}")
print(f"  Targets: {len(kb)}")
print(f"  Size: {kb_path.stat().st_size:,} bytes")
