/* CausaTwin v0.6 — 50 forward-looking cases with 6-config results */
/* Lock date: 2023-12-31; Gold = actual 2024 outcomes */
/* Generated 2026-09-23 from output/v06_*.json */

window.CAUSATWIN_V06_CASES = {
 "F1": {
  "id": "F1",
  "name": "Asundexian (F11)",
  "gene": "F11",
  "protein": "Coagulation factor XI",
  "indications": "Atrial fibrillation (stroke prevention)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral FXIa inhibitor)",
  "mechanism": "Factor XIa inhibition → reduced thrombin generation without bleeding risk",
  "gold_score": 6.3,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Reject",
  "actual_event": "OCEANIC-AF Phase 3 terminated for inferior efficacy (Aug 2024)",
  "novelty_score": 0.31,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.0,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": 2.0,
  "solo_A_decision": "Reject",
  "solo_B_score": null,
  "solo_B_decision": null,
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F2": {
  "id": "F2",
  "name": "VERVE-101 (PCSK9 base editing)",
  "gene": "PCSK9",
  "protein": "PCSK9",
  "indications": "Heterozygous familial hypercholesterolemia (HeFH)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 1b",
  "modality": "In vivo base editing (CRISPR/Cas9 + gRNA, lipid nanoparticle)",
  "mechanism": "Adenine base editor disrupts PCSK9 in hepatocytes",
  "gold_score": 5.2,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "VERVE-101 cardiac event (cholesterol elevation, troponin) 2024-09",
  "novelty_score": 0.897,
  "novelty_tier": "HIGH",
  "multi_A_score": 6.5,
  "multi_A_decision": "Advance",
  "multi_B_score": 5.0,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.5,
  "multi_C_decision": "Hold",
  "solo_A_score": 6.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 6.8,
  "solo_B_decision": "Advance",
  "solo_C_score": 6.5,
  "solo_C_decision": "Hold"
 },
 "F3": {
  "id": "F3",
  "name": "Vutrisiran (TTR)",
  "gene": "TTR",
  "protein": "Transthyretin",
  "indications": "ATTR cardiomyopathy (ATTR-CM)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "siRNA (GalNAc-conjugated)",
  "mechanism": "Hepatic TTR mRNA knockdown via GalNAc-RNAi",
  "gold_score": 7.8,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "HELIOS-B Phase 3 met primary endpoint (CV death + CV hosp) Jun 2024",
  "novelty_score": 0.44,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 7.2,
  "multi_A_decision": "Advance",
  "multi_B_score": 7.3,
  "multi_B_decision": "Advance",
  "multi_C_score": 8.2,
  "multi_C_decision": "Advance",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F4": {
  "id": "F4",
  "name": "Obicetrapib (CETP)",
  "gene": "CETP",
  "protein": "Cholesteryl ester transfer protein",
  "indications": "HeFH, ASCVD",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral CETP inhibitor)",
  "mechanism": "CETP inhibition → ↑HDL-C, ↓LDL-C",
  "gold_score": 6.4,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Reject",
  "actual_event": "BROADWAY Phase 3 failed primary LDL-C endpoint 2024",
  "novelty_score": 0.1,
  "novelty_tier": "LOW",
  "multi_A_score": 7.0,
  "multi_A_decision": "Advance",
  "multi_B_score": 5.2,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": null,
  "solo_B_decision": null,
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F5": {
  "id": "F5",
  "name": "Zilebesiran (AGT)",
  "gene": "AGT",
  "protein": "Angiotensinogen",
  "indications": "Mild-to-moderate hypertension",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 2 done",
  "modality": "siRNA (GalNAc-conjugated)",
  "mechanism": "Hepatic AGT mRNA knockdown → ↓AGT → ↓angiotensin II",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "KARDIA-3 Phase 2 failed to show additional BP benefit 2024",
  "novelty_score": 0.5,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 7.0,
  "multi_A_decision": "Advance",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 6.7,
  "multi_C_decision": "Advance",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.7,
  "solo_B_decision": "Advance",
  "solo_C_score": 2.5,
  "solo_C_decision": "Reject"
 },
 "F6": {
  "id": "F6",
  "name": "Lecanemab (AHEAD 3-45)",
  "gene": "APP",
  "protein": "Aβ protofibrils",
  "indications": "Preclinical Alzheimer disease",
  "disease_area": "Neurology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Humanized IgG1 mAb",
  "mechanism": "Anti-Aβ protofibril antibody",
  "gold_score": 4.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "AHEAD 3-45 stopped early for futility Oct 2024",
  "novelty_score": 0.06,
  "novelty_tier": "LOW",
  "multi_A_score": 4.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.0,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 8.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 7.5,
  "solo_C_decision": "Advance"
 },
 "F7": {
  "id": "F7",
  "name": "Mirikizumab (SHINE)",
  "gene": "IL23A",
  "protein": "IL-23 p19",
  "indications": "Crohn's disease",
  "disease_area": "Immunology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Humanized IgG4 mAb",
  "mechanism": "Anti-IL-23 p19 (different from IL-12/23 like ustekinumab)",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Reject",
  "actual_event": "SHINE Phase 3 failed CD primary endpoint 2024",
  "novelty_score": 0.15,
  "novelty_tier": "LOW",
  "multi_A_score": 5.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 7.6,
  "multi_C_decision": "Advance",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 8.2,
  "solo_B_decision": "Advance",
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F8": {
  "id": "F8",
  "name": "Linrodostat mesylate (PIVOT-IO 001)",
  "gene": "ADORA1",
  "protein": "Adenosine A1 receptor",
  "indications": "1L Renal cell carcinoma (combo with nivolumab)",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral A1AR antagonist)",
  "mechanism": "Adenosine A1 receptor antagonism → ↑T-cell activity in TME",
  "gold_score": 4.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "PIVOT-IO 001 Phase 3 failed to meet PFS endpoint 2024",
  "novelty_score": 0.29,
  "novelty_tier": "LOW",
  "multi_A_score": 1.5,
  "multi_A_decision": "Reject",
  "multi_B_score": 0.5,
  "multi_B_decision": "Reject",
  "multi_C_score": 1.5,
  "multi_C_decision": "Reject",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": null,
  "solo_B_decision": null,
  "solo_C_score": 2.5,
  "solo_C_decision": "Reject"
 },
 "F9": {
  "id": "F9",
  "name": "Zolbetuximab (SPOTLIGHT)",
  "gene": "CLDN18",
  "protein": "Claudin 18.2",
  "indications": "1L CLDN18.2+ gastric / GEJ adenocarcinoma",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 3 positive",
  "modality": "Chimeric IgG1 mAb",
  "mechanism": "Anti-CLDN18.2 ADCC",
  "gold_score": 7.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "SPOTLIGHT positive 2023, FDA approved Jan 2025",
  "novelty_score": 0.34,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 7.5,
  "multi_A_decision": "Advance",
  "multi_B_score": 7.0,
  "multi_B_decision": "Advance",
  "multi_C_score": null,
  "multi_C_decision": null,
  "solo_A_score": 9.0,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.7,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F10": {
  "id": "F10",
  "name": "Glofitamab (STARGLO)",
  "gene": "MS4A1;CD3E",
  "protein": "CD20 x CD3 bispecific",
  "indications": "2L+ DLBCL",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "CD20xCD3 bispecific antibody",
  "mechanism": "Bispecific T-cell engager",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "STARGLO Phase 3 met primary OS endpoint 2024",
  "novelty_score": 0.736,
  "novelty_tier": "HIGH",
  "multi_A_score": 4.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 6.3,
  "multi_B_decision": "Advance",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 7.5,
  "solo_C_decision": "Advance"
 },
 "F11": {
  "id": "F11",
  "name": "Fidanacogene elaparvovec (BENEGENE-2)",
  "gene": "F9",
  "protein": "Coagulation factor IX",
  "indications": "Hemophilia B",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 positive",
  "modality": "AAV5-based gene therapy",
  "mechanism": "AAV5-delivered Factor IX Padua transgene",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "BENEGENE-2 positive, FDA approved Apr 2024",
  "novelty_score": 0.653,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.0,
  "multi_B_decision": "Hold",
  "multi_C_score": 7.0,
  "multi_C_decision": "Advance",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 7.2,
  "solo_C_decision": "Advance"
 },
 "F12": {
  "id": "F12",
  "name": "Casgevy (CLIMB-131 / CLIMB-121)",
  "gene": "BCL11A",
  "protein": "BCL11A erythroid enhancer",
  "indications": "SCD and TDT",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 positive",
  "modality": "Ex vivo CRISPR-Cas9 cell therapy",
  "mechanism": "Disrupts BCL11A erythroid enhancer → reactivates HbF",
  "gold_score": 8.0,
  "gold_decision": "Advance",
  "actual_2024": "Advance",
  "actual_event": "CLIMB positive, FDA approved Dec 2023 (SCD), Jan 2024 (TDT)",
  "novelty_score": 0.897,
  "novelty_tier": "HIGH",
  "multi_A_score": 7.2,
  "multi_A_decision": "Advance",
  "multi_B_score": 6.8,
  "multi_B_decision": "Advance",
  "multi_C_score": 6.5,
  "multi_C_decision": "Advance",
  "solo_A_score": 9.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 9.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F13": {
  "id": "F13",
  "name": "Lyfgenia (HGB-206)",
  "gene": "HBB",
  "protein": "Hemoglobin beta",
  "indications": "Severe SCD",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 positive",
  "modality": "Lentiviral gene-modified HSC therapy",
  "mechanism": "Lentiviral βA-T87Q transgene addition",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Hold",
  "actual_event": "Approved with black box warning (hematologic malignancy), commercial very limited",
  "novelty_score": 0.738,
  "novelty_tier": "HIGH",
  "multi_A_score": 4.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 6.0,
  "multi_C_decision": "Advance",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 8.2,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.2,
  "solo_C_decision": "Advance"
 },
 "F14": {
  "id": "F14",
  "name": "Odronextamab (ELM-2)",
  "gene": "MS4A1;CD3E",
  "protein": "CD20 x CD3 bispecific",
  "indications": "R/R FL and DLBCL",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "CD20xCD3 bispecific antibody",
  "mechanism": "Bispecific T-cell engager",
  "gold_score": 5.0,
  "gold_decision": "Hold",
  "actual_2024": "Hold",
  "actual_event": "BLA filing delayed; conditional approval 2025",
  "novelty_score": 0.707,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.0,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": 7.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 5.2,
  "solo_B_decision": "Hold",
  "solo_C_score": 6.5,
  "solo_C_decision": "Advance"
 },
 "F15": {
  "id": "F15",
  "name": "Imetelstat (IMerge)",
  "gene": "TERC",
  "protein": "Telomerase RNA",
  "indications": "Lower-risk MDS",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 positive",
  "modality": "Lipid-conjugated oligonucleotide",
  "mechanism": "Direct telomerase competitive inhibitor",
  "gold_score": 6.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "IMerge positive, FDA approved Jun 2024 (Rytelo)",
  "novelty_score": 0.388,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 4.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 4.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 4.0,
  "multi_C_decision": "Hold",
  "solo_A_score": 8.8,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F16": {
  "id": "F16",
  "name": "Iclepertin (BI 425809)",
  "gene": "SLC6A9",
  "protein": "Glycine transporter 1 (GlyT1)",
  "indications": "Cognitive impairment in schizophrenia (CIAS)",
  "disease_area": "Neurology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral GlyT1 inhibitor)",
  "mechanism": "GlyT1 inhibition → ↑NMDA function → cognition",
  "gold_score": 5.0,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "CONNEX 1/2/3 Phase 3 all failed to meet primary endpoint in CIAS, BI 2024",
  "novelty_score": 0.18,
  "novelty_tier": "LOW",
  "multi_A_score": 5.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 4.2,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 7.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 1.0,
  "solo_C_decision": "Reject"
 },
 "F17": {
  "id": "F17",
  "name": "Relacorilant (CORT125134)",
  "gene": "NR3C1",
  "protein": "Glucocorticoid receptor",
  "indications": "1L Metastatic pancreatic ductal adenocarcinoma (PDAC) + nab-paclitaxel",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral GR antagonist)",
  "mechanism": "GR antagonism reverses cortisol-mediated chemo-resistance",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "GRACE Phase 3 failed to meet primary OS in PDAC, Corcept 2024",
  "novelty_score": 0.21,
  "novelty_tier": "LOW",
  "multi_A_score": 4.2,
  "multi_A_decision": "Hold",
  "multi_B_score": 4.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 4.5,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": null,
  "solo_B_decision": null,
  "solo_C_score": 1.0,
  "solo_C_decision": "Reject"
 },
 "F18": {
  "id": "F18",
  "name": "Avenciguat (BAY 1021189)",
  "gene": "GUCY1A1;GUCY1B1",
  "protein": "Soluble guanylate cyclase (sGC)",
  "indications": "Heart failure with preserved ejection fraction (HFpEF)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral sGC stimulator)",
  "mechanism": "sGC stimulation → ↑cGMP → vasodilation",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "Avenciguat Phase 3 in HFpEF failed primary endpoint, Bayer 2024",
  "novelty_score": 0.25,
  "novelty_tier": "LOW",
  "multi_A_score": 5.2,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.0,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 7.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F19": {
  "id": "F19",
  "name": "Danuglipron (PF-07081532)",
  "gene": "GLP1R",
  "protein": "GLP-1 receptor",
  "indications": "Obesity, T2DM",
  "disease_area": "Metabolic",
  "phase_at_lock": "Phase 2",
  "modality": "Small molecule (oral GLP-1 receptor agonist)",
  "mechanism": "Oral non-peptide GLP-1 receptor agonism",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Reject",
  "actual_event": "Danuglipron oral GLP-1 discontinued due to AEs, Pfizer Dec 2023",
  "novelty_score": 0.33,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": null,
  "multi_B_decision": null,
  "multi_C_score": 4.5,
  "multi_C_decision": "Hold",
  "solo_A_score": 2.0,
  "solo_A_decision": "Reject",
  "solo_B_score": 2.0,
  "solo_B_decision": "Reject",
  "solo_C_score": 2.5,
  "solo_C_decision": "Reject"
 },
 "F20": {
  "id": "F20",
  "name": "Simufilam (PTI-125)",
  "gene": "FLNA",
  "protein": "Filamin A",
  "indications": "Mild-to-moderate Alzheimer disease",
  "disease_area": "Neurology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral filamin A inhibitor)",
  "mechanism": "Binds altered filamin A → restores receptor function",
  "gold_score": 4.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "Simufilam Phase 3 REFOCUS/REFOCUS-AD failed, Cassava 2024",
  "novelty_score": 0.15,
  "novelty_tier": "LOW",
  "multi_A_score": 2.0,
  "multi_A_decision": "Reject",
  "multi_B_score": 1.5,
  "multi_B_decision": "Reject",
  "multi_C_score": 1.5,
  "multi_C_decision": "Reject",
  "solo_A_score": 3.0,
  "solo_A_decision": "Reject",
  "solo_B_score": 3.0,
  "solo_B_decision": "Reject",
  "solo_C_score": 1.0,
  "solo_C_decision": "Reject"
 },
 "F21": {
  "id": "F21",
  "name": "Narsoplimab (OMS721)",
  "gene": "MASP2",
  "protein": "Mannan-binding lectin serine protease 2",
  "indications": "IgA nephropathy (IgAN)",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Humanized mAb (IV MASP-2 inhibitor)",
  "mechanism": "Inhibits MASP-2 → blocks lectin complement pathway",
  "gold_score": 4.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "Narsoplimab FDA Adcom voted against approval in IgAN, Omeros 2024",
  "novelty_score": 0.2,
  "novelty_tier": "LOW",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 4.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 4.8,
  "multi_C_decision": "Hold",
  "solo_A_score": 2.5,
  "solo_A_decision": "Reject",
  "solo_B_score": 7.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F22": {
  "id": "F22",
  "name": "Elafibranor (GFT505)",
  "gene": "PPARA;PPARD",
  "protein": "PPAR-α/δ",
  "indications": "NASH / MASH",
  "disease_area": "Metabolic",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral dual PPAR-α/δ agonist)",
  "mechanism": "Dual PPAR-α/δ agonism → fatty acid oxidation + anti-inflammation",
  "gold_score": 4.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "RESOLVE-IT Phase 3 failed primary endpoint in NASH, Genfit 2020 (legacy)",
  "novelty_score": 0.29,
  "novelty_tier": "LOW",
  "multi_A_score": 2.5,
  "multi_A_decision": "Reject",
  "multi_B_score": 2.0,
  "multi_B_decision": "Reject",
  "multi_C_score": 4.2,
  "multi_C_decision": "Hold",
  "solo_A_score": 2.0,
  "solo_A_decision": "Reject",
  "solo_B_score": 2.0,
  "solo_B_decision": "Reject",
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F23": {
  "id": "F23",
  "name": "Selonsertib (GS-4997)",
  "gene": "MAP3K5",
  "protein": "Apoptosis signal-regulating kinase 1 (ASK1)",
  "indications": "NASH with F3-F4 fibrosis",
  "disease_area": "Metabolic",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral ASK1 inhibitor)",
  "mechanism": "ASK1 inhibition → ↓p38/JNK → ↓inflammation/fibrosis",
  "gold_score": 4.0,
  "gold_decision": "Reject",
  "actual_2024": "Reject",
  "actual_event": "STELLAR-3/4 Phase 3 failed in NASH, Gilead 2019-2020 (legacy)",
  "novelty_score": 0.27,
  "novelty_tier": "LOW",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 2.5,
  "multi_B_decision": "Reject",
  "multi_C_score": 2.0,
  "multi_C_decision": "Reject",
  "solo_A_score": 2.0,
  "solo_A_decision": "Reject",
  "solo_B_score": 2.5,
  "solo_B_decision": "Reject",
  "solo_C_score": 2.5,
  "solo_C_decision": "Reject"
 },
 "F24": {
  "id": "F24",
  "name": "Cenicriviroc (TBR-652)",
  "gene": "CCR2;CCR5",
  "protein": "CCR2/CCR5",
  "indications": "NASH with liver fibrosis",
  "disease_area": "Metabolic",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral CCR2/CCR5 antagonist)",
  "mechanism": "Dual CCR2/CCR5 antagonism → ↓monocyte recruitment → anti-fibrotic",
  "gold_score": 4.0,
  "gold_decision": "Reject",
  "actual_2024": "Reject",
  "actual_event": "AURORA Phase 3 failed primary endpoint, Allergan 2019 (legacy)",
  "novelty_score": 0.22,
  "novelty_tier": "LOW",
  "multi_A_score": 3.0,
  "multi_A_decision": "Reject",
  "multi_B_score": 2.0,
  "multi_B_decision": "Reject",
  "multi_C_score": 2.5,
  "multi_C_decision": "Reject",
  "solo_A_score": 1.5,
  "solo_A_decision": "Reject",
  "solo_B_score": 2.5,
  "solo_B_decision": "Reject",
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F25": {
  "id": "F25",
  "name": "Etripamil (Cardala)",
  "gene": "CACNA1C",
  "protein": "L-type Ca channel (Cav1.2)",
  "indications": "Paroxysmal supraventricular tachycardia (PSVT)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (intranasal L-type Ca channel blocker)",
  "mechanism": "Rapid-onset L-type Ca channel blockade → AV node slowing",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "NODE-301 etripamil in PSVT approved (Cardala, Milestone 2024)",
  "novelty_score": 0.3,
  "novelty_tier": "LOW",
  "multi_A_score": 4.5,
  "multi_A_decision": "Hold",
  "multi_B_score": null,
  "multi_B_decision": null,
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": 7.3,
  "solo_A_decision": "Advance",
  "solo_B_score": 7.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.2,
  "solo_C_decision": "Advance"
 },
 "F26": {
  "id": "F26",
  "name": "Verve-102 (PCSK9 base editing v2)",
  "gene": "PCSK9",
  "protein": "PCSK9",
  "indications": "HeFH / ASCVD",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 1b/2",
  "modality": "In vivo base editing (GalNAc-LNP, next-gen)",
  "mechanism": "Improved LNP delivery + GalNAc targeting → liver-specific PCSK9 disruption",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Hold",
  "actual_event": "Phase 1 ongoing, no major safety signals, Verve-102 in trials 2024",
  "novelty_score": 0.88,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 6.5,
  "multi_B_decision": "Advance",
  "multi_C_score": 5.2,
  "multi_C_decision": "Hold",
  "solo_A_score": 4.5,
  "solo_A_decision": "Hold",
  "solo_B_score": 5.2,
  "solo_B_decision": "Hold",
  "solo_C_score": 6.5,
  "solo_C_decision": "Advance"
 },
 "F27": {
  "id": "F27",
  "name": "Verve-201 (Lp(a) base editing)",
  "gene": "LPA",
  "protein": "Lipoprotein(a)",
  "indications": "ASCVD with elevated Lp(a)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 1",
  "modality": "In vivo base editing (CRISPR/Cas9 + gRNA, LNP)",
  "mechanism": "Disrupts LPA gene in hepatocytes → ↓Lp(a) lifelong",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Hold",
  "actual_event": "Phase 1 dose escalation ongoing, no readout 2024",
  "novelty_score": 0.92,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": null,
  "solo_B_decision": null,
  "solo_C_score": null,
  "solo_C_decision": null
 },
 "F28": {
  "id": "F28",
  "name": "NTLA-2002",
  "gene": "KLKB1",
  "protein": "Prekallikrein",
  "indications": "Hereditary angioedema (HAE)",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 1/2",
  "modality": "In vivo CRISPR-Cas9 (LNP-delivered)",
  "mechanism": "Disrupts KLKB1 gene → ↓prekallikrein → ↓bradykinin",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "NTLA-2002 Phase 1/2 positive interim data, Phase 3 planning 2024",
  "novelty_score": 0.89,
  "novelty_tier": "HIGH",
  "multi_A_score": 4.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 7.0,
  "multi_C_decision": "Advance",
  "solo_A_score": 7.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 7.6,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F29": {
  "id": "F29",
  "name": "EDIT-301 (reni-cel)",
  "gene": "HBG1;HBG2",
  "protein": "γ-globin (HbF)",
  "indications": "Severe SCD",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 1/2",
  "modality": "Ex vivo CRISPR-Cas12a edited HSC therapy",
  "mechanism": "Disrupts HBG promoter → reactivates HbF",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Advance",
  "actual_event": "EDIT-301 RUBY trial positive interim data, Editas 2024",
  "novelty_score": 0.86,
  "novelty_tier": "HIGH",
  "multi_A_score": 6.8,
  "multi_A_decision": "Advance",
  "multi_B_score": 6.5,
  "multi_B_decision": "Advance",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 7.2,
  "solo_B_decision": "Advance",
  "solo_C_score": 7.2,
  "solo_C_decision": "Advance"
 },
 "F30": {
  "id": "F30",
  "name": "BRL-101 (ET-01)",
  "gene": "HBB;HBG1;HBG2",
  "protein": "BCL11A",
  "indications": "Transfusion-dependent β-thalassemia (TDT)",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 1/2",
  "modality": "Ex vivo CRISPR-Cas9 HSC therapy",
  "mechanism": "Disrupts BCL11A erythroid enhancer (same target as Casgevy)",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Advance",
  "actual_event": "BRL-101 Phase 1/2 positive data in TDT, BRL Medicine 2024",
  "novelty_score": 0.87,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 7.8,
  "multi_B_decision": "Advance",
  "multi_C_score": 7.5,
  "multi_C_decision": "Advance",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 7.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F31": {
  "id": "F31",
  "name": "Aficamten (CK-274)",
  "gene": "MYH7",
  "protein": "Cardiac myosin",
  "indications": "Hypertrophic cardiomyopathy (HCM, oHCM)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 ongoing (SEQUOIA-HCM)",
  "modality": "Small molecule (oral cardiac myosin inhibitor)",
  "mechanism": "Selective cardiac myosin ATPase inhibitor → ↓hypercontractility",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "SEQUOIA-HCM positive, FDA approved (CAMZYOS competitor) 2025",
  "novelty_score": 0.38,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 7.0,
  "multi_B_decision": "Advance",
  "multi_C_score": 7.0,
  "multi_C_decision": "Advance",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 7.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.2,
  "solo_C_decision": "Advance"
 },
 "F32": {
  "id": "F32",
  "name": "Nemtabrutinib (MK-1026)",
  "gene": "BTK",
  "protein": "Bruton tyrosine kinase",
  "indications": "CLL, NHL",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 2/3",
  "modality": "Small molecule (oral non-covalent BTK inhibitor)",
  "mechanism": "Non-covalent BTK binding → overcomes C481 resistance",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Hold",
  "actual_event": "Nemtabrutinib Phase 2 mixed, Phase 3 ongoing 2024",
  "novelty_score": 0.4,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 6.7,
  "multi_B_decision": "Advance",
  "multi_C_score": 6.4,
  "multi_C_decision": "Advance",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 7.5,
  "solo_B_decision": "Conditional advance",
  "solo_C_score": 7.2,
  "solo_C_decision": "Advance"
 },
 "F33": {
  "id": "F33",
  "name": "RMC-6236",
  "gene": "KRAS;HRAS;NRAS",
  "protein": "RAS(ON) multi-selective",
  "indications": "KRAS G12X-mutant PDAC, NSCLC",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 1",
  "modality": "Small molecule (oral RAS(ON) tri-complex inhibitor)",
  "mechanism": "Pan-RAS(ON) inhibitor → blocks active GTP-bound RAS",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Hold",
  "actual_event": "RMC-6236 Phase 1 dose escalation ongoing, promising 2024",
  "novelty_score": 0.75,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": null,
  "multi_B_decision": null,
  "multi_C_score": 5.5,
  "multi_C_decision": "Hold",
  "solo_A_score": 7.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 7.2,
  "solo_B_decision": "Advance",
  "solo_C_score": 7.5,
  "solo_C_decision": "Advance"
 },
 "F34": {
  "id": "F34",
  "name": "Ciboterlipegogene bilparvovec (4D-310)",
  "gene": "REP1",
  "protein": "Rab Escort Protein 1 (CHM gene)",
  "indications": "Choroideremia",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 1/2",
  "modality": "AAV-based gene therapy (R100 capsid)",
  "mechanism": "Intravitreal AAV delivering REP1 for choroideremia",
  "gold_score": 5.0,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "4D-310 Phase 1/2 failed, 4DMT discontinued 2024",
  "novelty_score": 0.84,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 6.9,
  "multi_B_decision": "Advance",
  "multi_C_score": 5.5,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 6.8,
  "solo_B_decision": "Advance",
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 },
 "F35": {
  "id": "F35",
  "name": "Garadacimab (CSL312)",
  "gene": "F12",
  "protein": "Coagulation factor XIIa",
  "indications": "Hereditary angioedema (HAE)",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 ongoing (VANGUARD)",
  "modality": "Humanized IgG4 mAb (SC, monthly)",
  "mechanism": "Factor XIIa inhibition → ↓bradykinin",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "VANGUARD Phase 3 positive, CSL approved 2025",
  "novelty_score": 0.46,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.0,
  "multi_B_decision": "Hold",
  "multi_C_score": 7.5,
  "multi_C_decision": "Advance",
  "solo_A_score": 8.2,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 9.0,
  "solo_C_decision": "Advance"
 },
 "F36": {
  "id": "F36",
  "name": "Donanemab (TRAILBLAZER-ALZ 3)",
  "gene": "APP",
  "protein": "Aβ pyroglutamate (N3pE)",
  "indications": "Early symptomatic Alzheimer disease",
  "disease_area": "Neurology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Humanized IgG1 mAb",
  "mechanism": "Anti-Aβ pE3 (N-terminal pyroglutamate) plaque",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Advance",
  "actual_event": "TRAILBLAZER-ALZ 2 positive 2023, FDA approved (Kisunla) Jul 2024",
  "novelty_score": 0.18,
  "novelty_tier": "LOW",
  "multi_A_score": 5.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 4.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.5,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": null,
  "solo_B_decision": null,
  "solo_C_score": null,
  "solo_C_decision": null
 },
 "F37": {
  "id": "F37",
  "name": "Cobenfy (KarXT)",
  "gene": "CHRM1;CHRM4",
  "protein": "M1/M4 muscarinic receptors",
  "indications": "Schizophrenia",
  "disease_area": "Neurology",
  "phase_at_lock": "Phase 3 positive",
  "modality": "Small molecule (oral M1/M4 agonist + peripheral antagonist)",
  "mechanism": "Central M1/M4 agonism (xanomeline) + peripheral block (trospium) → no D2 side effects",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "EMERGENT-3 positive, FDA approved (Cobenfy) Sep 2024",
  "novelty_score": 0.4,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 4.5,
  "multi_A_decision": "Hold",
  "multi_B_score": null,
  "multi_B_decision": null,
  "multi_C_score": 6.8,
  "multi_C_decision": "Advance",
  "solo_A_score": 9.2,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F38": {
  "id": "F38",
  "name": "Tarlatamab (Imdelltra)",
  "gene": "DLL3;CD3E",
  "protein": "DLL3 x CD3 bispecific",
  "indications": "3L+ Small cell lung cancer (SCLC)",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 2",
  "modality": "DLL3 x CD3 BiTE",
  "mechanism": "Bispecific T-cell engager targeting DLL3 on SCLC",
  "gold_score": 6.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "DeLLphi-301 positive 2024, FDA approved (Imdelltra) May 2024",
  "novelty_score": 0.83,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.8,
  "multi_A_decision": "Hold",
  "multi_B_score": 7.0,
  "multi_B_decision": "Advance",
  "multi_C_score": null,
  "multi_C_decision": null,
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.7,
  "solo_C_decision": "Advance"
 },
 "F39": {
  "id": "F39",
  "name": "Vorasidenib (Voranigo)",
  "gene": "IDH1;IDH2",
  "protein": "Mutant IDH1/IDH2",
  "indications": "Grade 2 IDH-mutant glioma",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 3 positive",
  "modality": "Small molecule (oral brain-penetrant IDH1/2 inhibitor)",
  "mechanism": "Mutant IDH inhibition → ↓2-HG → reverses differentiation block",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "INDIGO positive, FDA approved (Voranigo) Aug 2024",
  "novelty_score": 0.52,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 7.3,
  "multi_A_decision": "Advance",
  "multi_B_score": 8.0,
  "multi_B_decision": "Advance",
  "multi_C_score": 7.0,
  "multi_C_decision": "Advance",
  "solo_A_score": 9.0,
  "solo_A_decision": "Advance",
  "solo_B_score": 9.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 9.0,
  "solo_C_decision": "Advance"
 },
 "F40": {
  "id": "F40",
  "name": "Iptacopan (Fabhalta)",
  "gene": "CFB",
  "protein": "Complement factor B",
  "indications": "Paroxysmal nocturnal hemoglobinuria (PNH)",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 positive",
  "modality": "Small molecule (oral factor B inhibitor)",
  "mechanism": "Complement factor B inhibition → blocks alternative pathway",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "APPLY-PNH positive, FDA approved (Fabhalta) Dec 2023",
  "novelty_score": 0.31,
  "novelty_tier": "LOW",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 6.5,
  "multi_B_decision": "Advance",
  "multi_C_score": 8.4,
  "multi_C_decision": "Advance",
  "solo_A_score": 9.2,
  "solo_A_decision": "Advance",
  "solo_B_score": 9.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.8,
  "solo_C_decision": "Advance"
 },
 "F41": {
  "id": "F41",
  "name": "Linvoseltamab (REGN5458)",
  "gene": "TNFRSF17;CD3E",
  "protein": "BCMA x CD3 bispecific",
  "indications": "R/R Multiple myeloma (MM)",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 1/2",
  "modality": "BCMA x CD3 bispecific antibody",
  "mechanism": "BCMA-directed T-cell engager",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "Linvoseltamab LINKER-MM3 positive 2024, BLA filed",
  "novelty_score": 0.72,
  "novelty_tier": "HIGH",
  "multi_A_score": 4.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 6.5,
  "multi_B_decision": "Advance",
  "multi_C_score": 5.2,
  "multi_C_decision": "Hold",
  "solo_A_score": null,
  "solo_A_decision": null,
  "solo_B_score": 8.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.2,
  "solo_C_decision": "Advance"
 },
 "F42": {
  "id": "F42",
  "name": "Revumenib (SNDX-5613)",
  "gene": "KMT2A;MEN1",
  "protein": "Menin",
  "indications": "KMT2A-rearranged / NPM1-mutant AML",
  "disease_area": "Oncology",
  "phase_at_lock": "Phase 1/2",
  "modality": "Small molecule (oral menin inhibitor)",
  "mechanism": "Menin-KMT2A interaction disruption",
  "gold_score": 6.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "AUGMENT-101 positive, FDA approved (Revuforj) Nov 2024",
  "novelty_score": 0.7,
  "novelty_tier": "HIGH",
  "multi_A_score": 5.6,
  "multi_A_decision": "Hold",
  "multi_B_score": 7.2,
  "multi_B_decision": "Advance",
  "multi_C_score": 7.2,
  "multi_C_decision": "Advance",
  "solo_A_score": 7.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.2,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F43": {
  "id": "F43",
  "name": "Donidalorsen (IONS-PKK-LRx)",
  "gene": "KLKB1",
  "protein": "Prekallikrein",
  "indications": "Hereditary angioedema (HAE)",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 ongoing (OASIS-HAE)",
  "modality": "GalNAc-conjugated antisense oligonucleotide (SC)",
  "mechanism": "Hepatic KLKB1 mRNA knockdown → ↓prekallikrein → ↓bradykinin",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "OASIS-HAE positive, FDA approved (Dawnzera) Aug 2025",
  "novelty_score": 0.44,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 6.9,
  "multi_A_decision": "Advance",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 7.2,
  "multi_C_decision": "Advance",
  "solo_A_score": 7.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F44": {
  "id": "F44",
  "name": "Sebetralstat (FOREVER)",
  "gene": "KLKB1",
  "protein": "Plasma kallikrein",
  "indications": "On-demand HAE",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Small molecule (oral plasma kallikrein inhibitor)",
  "mechanism": "Plasma kallikrein inhibition → ↓bradykinin",
  "gold_score": 6.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "FOREVER positive, BioCryst filed 2024, approved 2025",
  "novelty_score": 0.27,
  "novelty_tier": "LOW",
  "multi_A_score": 5.0,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.8,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.5,
  "multi_C_decision": "Hold",
  "solo_A_score": 8.4,
  "solo_A_decision": "Advance",
  "solo_B_score": 7.8,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F45": {
  "id": "F45",
  "name": "Olpasiran (AMG 890)",
  "gene": "LPA",
  "protein": "Lipoprotein(a)",
  "indications": "ASCVD with elevated Lp(a)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "siRNA (GalNAc-conjugated, SC)",
  "mechanism": "Hepatic LPA mRNA knockdown → ↓Lp(a) ~95%",
  "gold_score": 6.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Hold",
  "actual_event": "OCEAN(a)-DOSE positive Phase 2, Phase 3 OCEAN(a)-Outcomes ongoing 2024",
  "novelty_score": 0.55,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 8.5,
  "multi_A_decision": "Advance",
  "multi_B_score": 8.6,
  "multi_B_decision": "Advance",
  "multi_C_score": 7.8,
  "multi_C_decision": "Advance",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.7,
  "solo_C_decision": "Advance"
 },
 "F46": {
  "id": "F46",
  "name": "Sotatercept (Winrevair)",
  "gene": "ACVR2A",
  "protein": "Activin receptor type 2A",
  "indications": "Pulmonary arterial hypertension (PAH)",
  "disease_area": "Cardiovascular",
  "phase_at_lock": "Phase 3 positive (STELLAR)",
  "modality": "Fc-fusion protein (activin receptor trap, SC)",
  "mechanism": "Activin/GDF trap → rebalance BMP signaling → reverse vascular remodeling",
  "gold_score": 7.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "STELLAR Phase 3 positive, FDA approved (Winrevair) Mar 2024",
  "novelty_score": 0.6,
  "novelty_tier": "MEDIUM",
  "multi_A_score": 4.8,
  "multi_A_decision": "Hold",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 7.3,
  "multi_C_decision": "Advance",
  "solo_A_score": 9.0,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.5,
  "solo_B_decision": "Advance",
  "solo_C_score": 9.0,
  "solo_C_decision": "Advance"
 },
 "F47": {
  "id": "F47",
  "name": "Resmetirom (Rezdiffra)",
  "gene": "THRB",
  "protein": "Thyroid hormone receptor β",
  "indications": "MASH with F2-F3 fibrosis",
  "disease_area": "Metabolic",
  "phase_at_lock": "Phase 3 positive (MAESTRO-NASH)",
  "modality": "Small molecule (oral liver-directed THR-β agonist)",
  "mechanism": "Hepatic THR-β selective agonism → ↑fatty acid oxidation → ↓lipotoxicity",
  "gold_score": 7.0,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "MAESTRO-NASH positive, FDA approved (Rezdiffra) Mar 2024",
  "novelty_score": 0.35,
  "novelty_tier": "LOW",
  "multi_A_score": 7.8,
  "multi_A_decision": "Advance",
  "multi_B_score": 8.0,
  "multi_B_decision": "Advance",
  "multi_C_score": 7.2,
  "multi_C_decision": "Advance",
  "solo_A_score": 9.2,
  "solo_A_decision": "Advance",
  "solo_B_score": 9.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.7,
  "solo_C_decision": "Advance"
 },
 "F48": {
  "id": "F48",
  "name": "Depemokimab (GSK3511294)",
  "gene": "IL5",
  "protein": "IL-5",
  "indications": "Severe eosinophilic asthma",
  "disease_area": "Immunology",
  "phase_at_lock": "Phase 3 ongoing (SWIFT-1/2)",
  "modality": "Humanized IgG1 mAb (SC, every 6 months)",
  "mechanism": "Anti-IL-5 with extended half-life → sustained eosinophil suppression",
  "gold_score": 6.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Hold",
  "actual_event": "SWIFT-1/2 Phase 3 mixed, GSK strategy pivot 2024",
  "novelty_score": 0.19,
  "novelty_tier": "LOW",
  "multi_A_score": 7.0,
  "multi_A_decision": "Advance",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 8.0,
  "multi_C_decision": "Advance",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 8.7,
  "solo_B_decision": "Advance",
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F49": {
  "id": "F49",
  "name": "Atrasentan (ABT-627)",
  "gene": "EDNRA",
  "protein": "Endothelin A receptor",
  "indications": "IgA nephropathy (IgAN)",
  "disease_area": "Rare disease",
  "phase_at_lock": "Phase 3 ongoing (ALIGN)",
  "modality": "Small molecule (oral selective ETA antagonist)",
  "mechanism": "Endothelin A receptor antagonism → ↓proteinuria + ↓fibrosis",
  "gold_score": 6.5,
  "gold_decision": "Conditional Advance",
  "actual_2024": "Advance",
  "actual_event": "ALIGN Phase 3 positive interim, Chinook acquired by Novartis 2024",
  "novelty_score": 0.23,
  "novelty_tier": "LOW",
  "multi_A_score": 4.5,
  "multi_A_decision": "Hold",
  "multi_B_score": 6.5,
  "multi_B_decision": "Advance",
  "multi_C_score": 5.0,
  "multi_C_decision": "Hold",
  "solo_A_score": 8.5,
  "solo_A_decision": "Advance",
  "solo_B_score": null,
  "solo_B_decision": null,
  "solo_C_score": 8.5,
  "solo_C_decision": "Advance"
 },
 "F50": {
  "id": "F50",
  "name": "Brazikumab (MEDI2070)",
  "gene": "IL23A",
  "protein": "IL-23 p19",
  "indications": "Crohn's disease, UC",
  "disease_area": "Immunology",
  "phase_at_lock": "Phase 3 ongoing",
  "modality": "Humanized IgG2 mAb",
  "mechanism": "Anti-IL-23 p19 (similar to risankizumab, mirikizumab)",
  "gold_score": 5.5,
  "gold_decision": "Hold",
  "actual_2024": "Reject",
  "actual_event": "INTREPID Phase 3 failed primary endpoint in CD, AbbVie 2024",
  "novelty_score": 0.14,
  "novelty_tier": "LOW",
  "multi_A_score": 6.5,
  "multi_A_decision": "Advance",
  "multi_B_score": 5.5,
  "multi_B_decision": "Hold",
  "multi_C_score": 5.3,
  "multi_C_decision": "Hold",
  "solo_A_score": 7.5,
  "solo_A_decision": "Advance",
  "solo_B_score": 7.0,
  "solo_B_decision": "Advance",
  "solo_C_score": 2.0,
  "solo_C_decision": "Reject"
 }
};

window.CAUSATWIN_V06_MASTER = {
 "multi_A": {
  "n_total": 50,
  "n_correct": 17,
  "accuracy": 0.34,
  "mae": 1.17,
  "p_advance": 0.5384615384615384,
  "r_advance": 0.2916666666666667,
  "p_reject": 1.0,
  "r_reject": 0.2222222222222222,
  "n_hold_correct": 6,
  "by_novelty": {
   "MEDIUM": {
    "correct": 5,
    "total": 14
   },
   "HIGH": {
    "correct": 7,
    "total": 16
   },
   "LOW": {
    "correct": 5,
    "total": 20
   }
  },
  "by_case_type": {
   "F1-F15 (original v0.5)": {
    "correct": 6,
    "total": 15
   },
   "F16-F25 (non-novel failed)": {
    "correct": 3,
    "total": 10
   },
   "F26-F35 (high-novelty)": {
    "correct": 5,
    "total": 10
   },
   "F36-F50 (mature+novel mix)": {
    "correct": 3,
    "total": 15
   }
  }
 },
 "solo_A": {
  "n_total": 35,
  "n_correct": 28,
  "accuracy": 0.8,
  "mae": 1.917142857142857,
  "p_advance": 0.7407407407407407,
  "r_advance": 1.0,
  "p_reject": 1.0,
  "r_reject": 0.7,
  "n_hold_correct": 1,
  "by_novelty": {
   "MEDIUM": {
    "correct": 11,
    "total": 13
   },
   "HIGH": {
    "correct": 7,
    "total": 10
   },
   "LOW": {
    "correct": 10,
    "total": 12
   }
  },
  "by_case_type": {
   "F1-F15 (original v0.5)": {
    "correct": 7,
    "total": 10
   },
   "F16-F25 (non-novel failed)": {
    "correct": 7,
    "total": 7
   },
   "F26-F35 (high-novelty)": {
    "correct": 4,
    "total": 5
   },
   "F36-F50 (mature+novel mix)": {
    "correct": 10,
    "total": 13
   }
  }
 },
 "multi_B": {
  "n_total": 46,
  "n_correct": 23,
  "accuracy": 0.5,
  "mae": 1.0934782608695652,
  "p_advance": 0.7777777777777778,
  "r_advance": 0.6363636363636364,
  "p_reject": 1.0,
  "r_reject": 0.29411764705882354,
  "n_hold_correct": 4,
  "by_novelty": {
   "MEDIUM": {
    "correct": 4,
    "total": 12
   },
   "HIGH": {
    "correct": 10,
    "total": 15
   },
   "LOW": {
    "correct": 9,
    "total": 19
   }
  },
  "by_case_type": {
   "F1-F15 (original v0.5)": {
    "correct": 7,
    "total": 15
   },
   "F16-F25 (non-novel failed)": {
    "correct": 4,
    "total": 8
   },
   "F26-F35 (high-novelty)": {
    "correct": 4,
    "total": 9
   },
   "F36-F50 (mature+novel mix)": {
    "correct": 8,
    "total": 14
   }
  }
 },
 "solo_B": {
  "n_total": 43,
  "n_correct": 29,
  "accuracy": 0.6744186046511628,
  "mae": 1.7,
  "p_advance": 0.6285714285714286,
  "r_advance": 1.0,
  "p_reject": 1.0,
  "r_reject": 0.35714285714285715,
  "n_hold_correct": 2,
  "by_novelty": {
   "HIGH": {
    "correct": 11,
    "total": 15
   },
   "MEDIUM": {
    "correct": 10,
    "total": 13
   },
   "LOW": {
    "correct": 8,
    "total": 15
   }
  },
  "by_case_type": {
   "F1-F15 (original v0.5)": {
    "correct": 7,
    "total": 12
   },
   "F16-F25 (non-novel failed)": {
    "correct": 6,
    "total": 9
   },
   "F26-F35 (high-novelty)": {
    "correct": 6,
    "total": 9
   },
   "F36-F50 (mature+novel mix)": {
    "correct": 10,
    "total": 13
   }
  }
 },
 "multi_C": {
  "n_total": 48,
  "n_correct": 22,
  "accuracy": 0.4583333333333333,
  "mae": 0.8687500000000002,
  "p_advance": 0.7,
  "r_advance": 0.6363636363636364,
  "p_reject": 1.0,
  "r_reject": 0.2222222222222222,
  "n_hold_correct": 4,
  "by_novelty": {
   "MEDIUM": {
    "correct": 7,
    "total": 13
   },
   "HIGH": {
    "correct": 9,
    "total": 15
   },
   "LOW": {
    "correct": 6,
    "total": 20
   }
  },
  "by_case_type": {
   "F1-F15 (original v0.5)": {
    "correct": 5,
    "total": 14
   },
   "F16-F25 (non-novel failed)": {
    "correct": 3,
    "total": 10
   },
   "F26-F35 (high-novelty)": {
    "correct": 7,
    "total": 10
   },
   "F36-F50 (mature+novel mix)": {
    "correct": 7,
    "total": 14
   }
  }
 },
 "solo_C": {
  "n_total": 48,
  "n_correct": 39,
  "accuracy": 0.8125,
  "mae": 2.2395833333333335,
  "p_advance": 0.7419354838709677,
  "r_advance": 1.0,
  "p_reject": 1.0,
  "r_reject": 0.8888888888888888,
  "n_hold_correct": 0,
  "by_novelty": {
   "MEDIUM": {
    "correct": 12,
    "total": 14
   },
   "HIGH": {
    "correct": 10,
    "total": 15
   },
   "LOW": {
    "correct": 17,
    "total": 19
   }
  },
  "by_case_type": {
   "F1-F15 (original v0.5)": {
    "correct": 11,
    "total": 15
   },
   "F16-F25 (non-novel failed)": {
    "correct": 10,
    "total": 10
   },
   "F26-F35 (high-novelty)": {
    "correct": 6,
    "total": 9
   },
   "F36-F50 (mature+novel mix)": {
    "correct": 12,
    "total": 14
   }
  }
 }
};
